---

- name: "ADD Python string comments"
  block:
  - name: "Add String marker"
    lineinfile:
      path: "{{ file_path }}/{{ md_code_file }}"
      insertbefore: 'ansible generated process flow wireframe for {{ md_code_file }}'
      line: "--- \n  \n### Python String Comments:  \n  "
  # write out Comments to the file
  - name: "ADD string comments"
    lineinfile:
      path: "{{ file_path }}/{{ md_code_file }}"
      insertbefore: 'ansible generated process flow wireframe for {{ md_code_file }}'
      line: "{{ PY_STYLE }}"
    with_file: "{{code_file}}"
  when: (file_extension == "py")


- name: "Add comment marker to {{ md_code_file }}"
  lineinfile:
    path: "{{ file_path }}/{{ md_code_file }}"
    insertbefore: 'ansible generated process flow wireframe for {{ md_code_file }}'
    line: "--- \n  \n### Comments:  \n  "
# write out Comments to the file
- name: "Add comments to {{ md_code_file }}"
  lineinfile:
    path: "{{ file_path }}/{{ md_code_file }}"
    insertbefore: 'ansible generated process flow wireframe for {{ md_code_file }}'
    line: "{{ HASH_STYLE }}"
  with_file: "{{code_file}}"
