---

# write out Comments to the file
- name: "Add Comments to {{ md_code_file }}"
  lineinfile:
    path: "{{ file_path }}/{{ md_code_file }}"
    insertbefore: 'ansible generated process flow wireframe for {{ md_code_file }}'
    line: "--- \n  \n### Comments:  \n  "
- name: "Add comments to {{ md_code_file }}"
  lineinfile:
    path: "{{ file_path }}/{{ md_code_file }}"
    insertbefore: 'ansible generated process flow wireframe for {{ md_code_file }}'
    line: "{{ SLASH_STYLE }}"
  with_file: "{{code_file}}"
