---

- name: "ADD meta"
  block:
  - name: "Add Meta marker"
    lineinfile:
      path: "{{ file_path }}/{{ md_code_file }}"
      insertbefore: 'ansible generated process flow wireframe for {{ md_code_file }}'
      line: "--- \n  \n### Meta:  \n  "
  # write out Comments to the file
  - name: "ADD meta comments"
    lineinfile:
      path: "{{ file_path }}/{{ md_code_file }}"
      insertbefore: 'ansible generated process flow wireframe for {{ md_code_file }}'
      line: "{{ META_STYLE }}"
    with_file: "{{code_file}}"



# write out Comments to the file
- name: "ADD Comment marker"
  lineinfile:
    path: "{{ file_path }}/{{ md_code_file }}"
    insertbefore: 'ansible generated process flow wireframe for {{ md_code_file }}'
    line: "--- \n  \n### Comments:  \n  "
- name: "ADD Comments"
  lineinfile:
    path: "{{ file_path }}/{{ md_code_file }}"
    insertbefore: 'ansible generated process flow wireframe for {{ md_code_file }}'
    line: "{{ WEB_STYLE }}"
  with_file: "{{code_file}}"
